language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: ARn2nT99Bc4Iv4W+PqC5eqTL4etonCD/HUsCWRnPusbFyp6/8eZHwrdliu0eXZcdk2+1A9LM1mm6zvL2UdQL9P10wMX2EVn2zDiUIT+BMiDtTwoNKiPx49w9FC1B5CoXnegfB4XPwFQVD2SJbA2kTEi8PmJWF4slBVtZ7Yp4jSyT5xYhVXAAwDu70TWAGkBWnwaPRPKdQ4ok0/3/vcTDiHnHaL7oJyG3ZvgKtQedRo6UODIVekjMoAT1m8XDXc61PxkJ4Lexbqwfu7Jfc9C1tjBgDxc6zitMJtIc84yOlZPGAKoTpAOYcEmAIdRwHnN2L0rltnF9s3R1FYnTBCnyVxK6S9q2o5WkKWp07R9eqIwj19uiHf+2oKm8zYkmRSkC8RF4YuA4hZA4h5ERr+PLL7V3vGQBcQOlwLa22n/5wMQaRDV2MR8xRSxEN4ULL/S858rd2xbi7XIM3AY/ojQj8Ns9PWUEGwfJ/nxIt/XjSVUHHNUubWs6cakmrP/QKP8mERVTz52NiAO8a/lXdzLclPxwKoEDs0aXlhQVQWmeAIw5MGtmwoggMswK1VdLhCWVsEUVo/ekAJdJ0eDGZLMZZ6TvKxd8l1zovANLpYCJkkYWn7xQioPJVsr2ixzleHuGLZj9PEEw3tflYe16uL3eOC0utyT+YlKAUyFgqHZ7dIo=
  app: montrose-dishes
  on:
    repo: lacewaves/montrose-dishes
  run:
    - "rake db:migrate"
    - "rake cleanup"
