language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: QwTGKy3CJDKb+/fcgU6oJgwvB25OyvzHEVT9zKc38HuT0k8vxExo4OeYmP/rNFYTQNDQZrwx49kMeAYpJRX039hgjv1K2YjewCX1NHUnlahSkJC94PIjlJmV8V/lBtax8velEolJABAReCeWCLWOrmeAjGszId7HhJDSDc7vmxWUJBWSFoejaUzuYBHxoYxjja/vg1iwsGOj4pT/SrOcLRJiRY2Bx4jBlhHgVlSbOQEgnis34DJdCn8ZMcsgnGyViAO0b0vMz1dpVP8GQ5q/OFjyMgPBAldnxQenxmBFRCG57hgqUiU+cHMup1TcJBtnxRsYYWpNpiu0SBs1qqwtOZeaJeHkCOtfyUXIP70QMKUzUgpKUYxvOX+e8FZYce3VFxNmg+nzz9pFPaq1Dl0k33SlT4ODX+1x2VEPue6USYAc+eATPFe1hPKZ9Fecj3aatDnvh363KKReI+GbqEFheg+5bcCu4oWdzwcga1/OiQm3Cbrpd9i8g9gECMc8hpP8jtM4vSD1cn7hFsPsVQqnbwse7EzIlGURRgQc5WVlYL2m3rWATwzDoWhV9iOeFzERY2rVfCXzeRbtdMRCA86RlXBcFdfiGFrWw+Ep0I82dWEbfIwQUrHBUF50Jv/pOIyHTjx93RIYCb7ragG0NKWehI6s9q+HOMURyR1X807Fzvs=
  app: still-mesa-4051
  on:
    repo: lacewaves/montrose-dishes
  run:
    - "rake db:migrate"
    - "rake cleanup"
