language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: AiC94iFTU2JDaoEegqU/rmP5a8FkwCbeGhsMT1QCCDExLscIlaGzhBvCoBEWMr9P6p4cSfJGV8APmCapsYU8xYN3VMzIWcZR9VxZXk5VIIzrELL8ZNZNIk8Q2Nbpl95TiPrMu5WiZS3RBf2yVbfu0Y4znG94URnzpf6kWpEoGr4STuR1PKyojQkxxVUrCBcxiKeRlMu28hKw56jti6S1XHHFwIltsnszTBZs372V3/jS7JTZWvxJMCr6Z8lcrQRNV0USHKOPoxyo2EsH7Gu3Ss1TC2Z6Ke6eCIXo10I+P3UkGY83YpzwvMDInHunFh/nK5tvQ6NmDJEVY6U+BmL9eqJWqea2TskWizugO762QBQP9D28NJb8sk7g1mSwABKTf07okH7v9ScBTmX3WJESGaCZM8poYMoSmzYb/Yb5QCFmBUvnqp+WwKdW0i1FQ2QHkJfJEUxX/iLUGh8hYo57H5Yn7Rxdhxg5Ax1UMIhcCnpFnto0qAIpktDjq430wAzkArXu482iSgJRTOs9kEbiyqM7QDpPjtwb2XfhAaHoqGmZob6sZXoQPG0qgQESAPm3dkWmp6FEiskyv0UdzTYVQQdfIXSp64GTX+SG8umg07V+1a+ifnmACufHKE9bmj/BFHA+TsMrN9KdBwd9Z5n9xiSsOA7Iqzp1XWq4AgMse54=
  app: still-mesa-4051
  on:
    repo: lacewaves/montrose-dishes
  run:
    - "rake db:migrate"
    - "rake cleanup"
